### ISSUE TITLE
Error when sending HTML template from View

### ISSUE THREAD

**Issue by anthonykusuma** [olimortimer/CodeIgniter-Mailgun-Library#1]
**Severity: 4096
Message: Object of class CI_Loader could not be converted to string**

`$this->email->to('to@email.com')
                        ->from('from@email.com','DDD - ONLINE ORDER')
                        ->subject('NEW EMAIL')
                        ->message($this->load->view('email_template'))
                        ->send();`

**Comment by olimortimer** [comment]
@anthonykusuma what version of CI?  It might be because you're trying to echo the view, rather than just returning it.  See https://stackoverflow.com/a/45637084

Try the following:

`$this->email->to('to@email.com') ->from('from@email.com','DDD - ONLINE ORDER') ->subject('NEW EMAIL') ->message($this->load->view('email_template', '', true)) ->send();`

**Comment by anthonykusuma** [comment]
@olimortimer hello, I use the latest version of CI (3.1.10). Thank you for your suggestion, I will give it a try and let you know soon.
